### ISSUE TITLE
Include TT shuttle deadline date, time, and time zone on website(s)

### ISSUE THREAD

**Issue by algofoogle** [TinyTapeout/tinytapeout_www#101]
When trying to plan an all-nighter push to complete a TT submission, it would help a lot to know what the exact deadline date & time is, inc. time zone. Right now, I have to do arithmetic on the countdown timer. Better yet would be some way to convert this to my local time zone (even a link to something that does it from the fixed time in UTC or CEST or whatever).

The tinytapeout.com homepage countdown is the main place, but there's also app.tinytapeout.com, where even a tooltip would do, e.g. `2024-09-06 20:00 UTC` (that IS the deadline for TT08, right?)

![image](https://github.com/user-attachments/assets/5871d9ca-f6c1-4316-81b6-724419adb79f)

**Comment by urish** [comment]
Good idea, thanks for opening an issue!

Added a tooltip, as suggested, in your local timezone:

![image](https://github.com/user-attachments/assets/ac938827-b200-43de-81c9-04b8b5ce3bc3)
