### ISSUE TITLE
Update references from Caravel to OpenFrame / prune out

### ISSUE THREAD

**Issue by thexeno** [TinyTapeout/tinytapeout_www#116]
In the clock section
https://github.com/TinyTapeout/tinytapeout_www/blob/main/content/specs/clock/_index.md

And also the gpios https://github.com/TinyTapeout/tinytapeout_www/blob/main/content/specs/gpio/_index.md

There is reference to the Caravel as the up to date solution (tt04+). I guess it needs to be pruned out to avoid confusion, as in the Discord is told we don't use it anymore, but this is the official website too.

**Comment by urish** [comment]
Thanks, done!
