### ISSUE TITLE
Homepage - ambiguous Tiles/PCBs count

### ISSUE THREAD

**Issue by DeflateAwning** [TinyTapeout/tinytapeout_www#66]
Can you please confirm if the counts on the homepage (e.g., "21/100 tiles") are the number of remaining tiles or the number of sold tiles?

It would be awesome if it said "21/100 tiles sold" or "21/100 tiles available" to make it more clear.

**Comment by urish** [comment]
@mattvenn any idea how to address it without cluttering the page?

**Comment by mattvenn** [comment]
make the 21 the same colour as the bar chart? 

put a 'sold so far' above the charts?

append 'sold' to each stat: '21/100 tiles sold' ?

**Comment by DeflateAwning** [comment]
I'm a fan of appending the word "sold"

**Comment by urish** [comment]
thoughts?

![image](https://github.com/TinyTapeout/tinytapeout_www/assets/892318/023cd553-5b6d-4ab0-b667-f280292fac29)

**Comment by DeflateAwning** [comment]
Looks good to me! Alternative, if you like it more:
![image](https://github.com/TinyTapeout/tinytapeout_www/assets/11021263/544dfe90-059b-4bc5-983e-962a261f2ece)

**Comment by urish** [comment]
How about just showing percentages instead of numbers?

![image](https://github.com/TinyTapeout/tinytapeout_www/assets/892318/acbbba46-0b48-4a9b-8639-95e4f69c2b4e)

**Comment by mattvenn** [comment]
yes, even simpler.

**Comment by urish** [comment]
There we have it. Thanks again @DeflateAwning for the feedback!
