### ISSUE TITLE
add a section showing how to set a default

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tinytapeout_www#91]
https://github.com/TinyTapeout/tinytapeout_www/blob/b4f99aadc0caf146d771c2e38a08d7ca6fbf6f3f/content/guides/get-started-demoboard/_index.md?plain=1#L274

example is Uri's simon project. show how to change the config file to make this design the default.

**Comment by psychogenic** [comment]
Yeah, can do.
